### ISSUE TITLE
Parset smoothing

### ISSUE THREAD

**Issue by RomeshA** [atomicateam/atomica#334]
Linear interpolation makes sense as the base level functionality, but there is still a need to be able to selectively smooth parameters. The root problem with pchip() as the underlying method is that it can produce unexpected results that the user has little control over.

The desired functionality is to be able to have parameters follow a smoothed version of the data. The proposed enhancement is to add a smoothing operation for `Parameter` and `ParameterSet` instances, that would result in them being explicitly smoothed with a choice of interpolation methods. Further, it would be possible to support even more aggressive smoothing (e.g. a curve that doesn't have to go through all of the data points) that would not be appropriate to provide via the baseline interpolation.

Functionality would likely be something like

```
Parameter.smooth(options)
```

to smooth an individual parameter, or

```
ParameterSet.smooth(options)
```

to smooth all parameters (or maybe a named subset) with certain options.

Could also consider a workflow like

```
smoothed_parset = P.parsets[0].smooth()
```

where the smoothing returns a copy rather than modifying the original instance - this mirrors pandas dataframes more closely, but since PlotData performs operations like interpolation in-place, it would probably be better for users not to trust that methods will not change their instances (i.e. to modify in-place consistently)

**Comment by cliffckerr** [comment]
The function `sc.smoothinterp()` was intended for this purpose, and although it's not perfect, might be a relatively quick way to implement this. I've been working on a manuscript outlining a more general purpose smoothing method, but no one should hold their breath for that :)

**Comment by RomeshA** [comment]
Merged in
