### ISSUE TITLE
Loading tables sometimes fails

### ISSUE THREAD

**Issue by Rowanmh** [atomicateam/atomica#373]
Typically read_table() in excel.py loads in a sequence of rows, if they have content: added to the current table, a blank row means finish that table. Keep reading in tables until reaching the end.

Typically a blank row looks like `(<EmptyCell>, <EmptyCell>, <EmptyCell>, <EmptyCell>, <EmptyCell>, <EmptyCell>, <EmptyCell>, <EmptyCell>, <EmptyCell>, <EmptyCell>, <EmptyCell>, <EmptyCell>, <EmptyCell>, <EmptyCell>, <EmptyCell>, <EmptyCell>, <EmptyCell>, <EmptyCell>)`
-> so it passes the `if len(row) == 0 ` test.

_sometimes_ a blank row looks like `()` and does not pass that test so it just gets skipped as if it's an #ignore row, and it adds what _should_ be the next table onto the current table while loading, and then the loading script generates all kinds of weird errors.

Seems like it can manually be "fixed" to get a spreadsheet to load by adding some formatting to blank rows so that they are <EmptyCell>'s rather than just being a blank row, but a more robust solution would be valuable - e.g. replacing the `if len(row) == 0 ` but that seems necessary to prevent a different error (?)

**Comment by RomeshA** [comment]
[malaria_framework_20191213_uncapped_prob.xlsx](https://github.com/atomicateam/atomica/files/3971942/malaria_framework_20191213_uncapped_prob.xlsx)
[Uploading Databook_SUB_DESERTIQUE_madagascar_20191213_uncapped_prob.xlsx…]()

**Comment by RomeshA** [comment]
[Databook_SUB_DESERTIQUE_madagascar_20191213_uncapped_prob.xlsx](https://github.com/atomicateam/atomica/files/3971945/Databook_SUB_DESERTIQUE_madagascar_20191213_uncapped_prob.xlsx)

**Comment by RomeshA** [comment]
The example files now work in `develop`, hopefully the latest updates are more robust in general, let's open a new issue if a new broken example comes up
