### ISSUE TITLE
Export ProjectFramework

### ISSUE THREAD

**Issue by RomeshA** [atomicateam/atomica#393]
It should be possible to export a ProjectFramework into an Excel file that can then be read back in. Due to populating defaults, it may not be an exact replica of the original framework. But the main point is that if a ProjectFramework has been programmatically modified, it could be validated in Excel using this functionality

**Comment by RomeshA** [comment]
Actually this is already implemented in `ProjectFramework.to_spreadsheet()` and `ProjectFramework.save_new()` (noting that `ProjectFramework.save()` will write the original Excel file including original comments and formatting, rather than generating a new spreadsheet based on the content of the `ProjectFramework` instance, as per `ProjectFramework.to_spreadsheet()`.

This functionality dates back to the original plan not to support programmatically modifying frameworks, but this workflow is looking to be increasingly common. We could consider swapping these methods around, so that `ProjectFramework.save()` writes the current contents in line with `ProjectData` and `ProgramSet`, and `ProjectFramework.save_original()` would save the original one? @Rowanmh ?

**Comment by Rowanmh** [comment]
@RomeshA tricky question.

The workflow of needing to save the 'original' framework has been rare to date (as most project files and frameworks we've worked with are created dynamically from the excel files on runtime). Saving (exporting?) a modified framework is likely to be more common.

It could almost be an argument to the same `.save` function...  or have `save_new` and `save_original` with no basic `save` to ensure disambiguation?

**Comment by RomeshA** [comment]
@Rowanmh My preference would be not to switch the behaviour dramatically with an argument, but maybe `save_original` doesn't need to be a method at all - `ProjectFramework.spreadsheet` is a `ScirisSpreadsheet` with the original spreadsheet, but the name of that attribute is now a little ambiguous because of the new workflow. That spreadsheet object already has the appropriate save methods that get wrapped by `ProjectFramework.save()` at the moment, so maybe the answer would be to rename this attribute such that for a `F = ProjectFramework(...)` it would be

- `F.save()` - save the actual (possibly modified) framework
- `F.original.save()` - Save the original spreadsheet (`F.original` is a `ScirisSpreadsheet`)

**Comment by Rowanmh** [comment]
@RomeshA I like that solution a lot!
